package com.brainybrawl.app.game.engine
internal val numberWords=mapOf(
"zero" to "0",
"zéro" to "0",
"صفر" to "0",
"one" to "1",
"un" to "1",
"واحد" to "1",
"two" to "2",
"deux" to "2",
"اثنان" to "2",
"three" to "3",
"trois" to "3",
"ثلاثة" to "3",
"four" to "4",
"quatre" to "4",
"أربعة" to "4",
"five" to "5",
"cinq" to "5",
"خمسة" to "5",
"six" to "6",
"six" to "6",
"ستة" to "6",
"seven" to "7",
"sept" to "7",
"سبعة" to "7",
"eight" to "8",
"huit" to "8",
"ثمانية" to "8",
"nine" to "9",
"neuf" to "9",
"تسعة" to "9",
"ten" to "10",
"dix" to "10",
"عشرة" to "10",
"eleven" to "11",
"onze" to "11",
"أحد عشر" to "11",
"twelve" to "12",
"douze" to "12",
"اثنا عشر" to "12",
"thirteen" to "13",
"treize" to "13",
"ثلاثة عشر" to "13",
"fourteen" to "14",
"quatorze" to "14",
"أربعة عشر" to "14",
"fifteen" to "15",
"quinze" to "15",
"خمسة عشر" to "15",
"sixteen" to "16",
"seize" to "16",
"ستة عشر" to "16",
"seventeen" to "17",
"dix-sept" to "17",
"سبعة عشر" to "17",
"eighteen" to "18",
"dix-huit" to "18",
"ثمانية عشر" to "18",
"nineteen" to "19",
"dix-neuf" to "19",
"تسعة عشر" to "19",
"twenty" to "20",
"vingt" to "20",
"عشرون" to "20",
"twenty-one" to "21",
"vingt et un" to "21",
"واحد و عشرون" to "21",
"twenty-two" to "22",
"vingt-deux" to "22",
"اثنان و عشرون" to "22",
"twenty-three" to "23",
"vingt-trois" to "23",
"ثلاثة و عشرون" to "23",
"twenty-four" to "24",
"vingt-quatre" to "24",
"أربعة و عشرون" to "24",
"twenty-five" to "25",
"vingt-cinq" to "25",
"خمسة و عشرون" to "25",
"twenty-six" to "26",
"vingt-six" to "26",
"ستة و عشرون" to "26",
"twenty-seven" to "27",
"vingt-sept" to "27",
"سبعة و عشرون" to "27",
"twenty-eight" to "28",
"vingt-huit" to "28",
"ثمانية و عشرون" to "28",
"twenty-nine" to "29",
"vingt-neuf" to "29",
"تسعة و عشرون" to "29",
"thirty" to "30",
"trente" to "30",
"ثلاثون" to "30",
"thirty-one" to "31",
"trente et un" to "31",
"واحد و ثلاثون" to "31",
"thirty-two" to "32",
"trente-deux" to "32",
"اثنان و ثلاثون" to "32",
"thirty-three" to "33",
"trente-trois" to "33",
"ثلاثة و ثلاثون" to "33",
"thirty-four" to "34",
"trente-quatre" to "34",
"أربعة و ثلاثون" to "34",
"thirty-five" to "35",
"trente-cinq" to "35",
"خمسة و ثلاثون" to "35",
"thirty-six" to "36",
"trente-six" to "36",
"ستة و ثلاثون" to "36",
"thirty-seven" to "37",
"trente-sept" to "37",
"سبعة و ثلاثون" to "37",
"thirty-eight" to "38",
"trente-huit" to "38",
"ثمانية و ثلاثون" to "38",
"thirty-nine" to "39",
"trente-neuf" to "39",
"تسعة و ثلاثون" to "39",
"forty" to "40",
"quarante" to "40",
"أربعون" to "40",
"forty-one" to "41",
"quarante et un" to "41",
"واحد و أربعون" to "41",
"forty-two" to "42",
"quarante-deux" to "42",
"اثنان و أربعون" to "42",
"forty-three" to "43",
"quarante-trois" to "43",
"ثلاثة و أربعون" to "43",
"forty-four" to "44",
"quarante-quatre" to "44",
"أربعة و أربعون" to "44",
"forty-five" to "45",
"quarante-cinq" to "45",
"خمسة و أربعون" to "45",
"forty-six" to "46",
"quarante-six" to "46",
"ستة و أربعون" to "46",
"forty-seven" to "47",
"quarante-sept" to "47",
"سبعة و أربعون" to "47",
"forty-eight" to "48",
"quarante-huit" to "48",
"ثمانية و أربعون" to "48",
"forty-nine" to "49",
"quarante-neuf" to "49",
"تسعة و أربعون" to "49",
"fifty" to "50",
"cinquante" to "50",
"خمسون" to "50",
"fifty-one" to "51",
"cinquante et un" to "51",
"واحد و خمسون" to "51",
"fifty-two" to "52",
"cinquante-deux" to "52",
"اثنان و خمسون" to "52",
"fifty-three" to "53",
"cinquante-trois" to "53",
"ثلاثة و خمسون" to "53",
"fifty-four" to "54",
"cinquante-quatre" to "54",
"أربعة و خمسون" to "54",
"fifty-five" to "55",
"cinquante-cinq" to "55",
"خمسة و خمسون" to "55",
"fifty-six" to "56",
"cinquante-six" to "56",
"ستة و خمسون" to "56",
"fifty-seven" to "57",
"cinquante-sept" to "57",
"سبعة و خمسون" to "57",
"fifty-eight" to "58",
"cinquante-huit" to "58",
"ثمانية و خمسون" to "58",
"fifty-nine" to "59",
"cinquante-neuf" to "59",
"تسعة و خمسون" to "59",
"sixty" to "60",
"soixante" to "60",
"ستون" to "60",
"sixty-one" to "61",
"soixante et un" to "61",
"واحد و ستون" to "61",
"sixty-two" to "62",
"soixante-deux" to "62",
"اثنان و ستون" to "62",
"sixty-three" to "63",
"soixante-trois" to "63",
"ثلاثة و ستون" to "63",
"sixty-four" to "64",
"soixante-quatre" to "64",
"أربعة و ستون" to "64",
"sixty-five" to "65",
"soixante-cinq" to "65",
"خمسة و ستون" to "65",
"sixty-six" to "66",
"soixante-six" to "66",
"ستة و ستون" to "66",
"sixty-seven" to "67",
"soixante-sept" to "67",
"سبعة و ستون" to "67",
"sixty-eight" to "68",
"soixante-huit" to "68",
"ثمانية و ستون" to "68",
"sixty-nine" to "69",
"soixante-neuf" to "69",
"تسعة و ستون" to "69",
"seventy" to "70",
"soixante-dix" to "70",
"سبعون" to "70",
"seventy-one" to "71",
"soixante et onze" to "71",
"واحد و سبعون" to "71",
"seventy-two" to "72",
"soixante-douze" to "72",
"اثنان و سبعون" to "72",
"seventy-three" to "73",
"soixante-treize" to "73",
"ثلاثة و سبعون" to "73",
"seventy-four" to "74",
"soixante-quatorze" to "74",
"أربعة و سبعون" to "74",
"seventy-five" to "75",
"soixante-quinze" to "75",
"خمسة و سبعون" to "75",
"seventy-six" to "76",
"soixante-seize" to "76",
"ستة و سبعون" to "76",
"seventy-seven" to "77",
"soixante-dix-sept" to "77",
"سبعة و سبعون" to "77",
"seventy-eight" to "78",
"soixante-dix-huit" to "78",
"ثمانية و سبعون" to "78",
"seventy-nine" to "79",
"soixante-dix-neuf" to "79",
"تسعة و سبعون" to "79",
"eighty" to "80",
"quatre-vingts" to "80",
"ثمانون" to "80",
"eighty-one" to "81",
"quatre-vingt-un" to "81",
"واحد و ثمانون" to "81",
"eighty-two" to "82",
"quatre-vingt-deux" to "82",
"اثنان و ثمانون" to "82",
"eighty-three" to "83",
"quatre-vingt-trois" to "83",
"ثلاثة و ثمانون" to "83",
"eighty-four" to "84",
"quatre-vingt-quatre" to "84",
"أربعة و ثمانون" to "84",
"eighty-five" to "85",
"quatre-vingt-cinq" to "85",
"خمسة و ثمانون" to "85",
"eighty-six" to "86",
"quatre-vingt-six" to "86",
"ستة و ثمانون" to "86",
"eighty-seven" to "87",
"quatre-vingt-sept" to "87",
"سبعة و ثمانون" to "87",
"eighty-eight" to "88",
"quatre-vingt-huit" to "88",
"ثمانية و ثمانون" to "88",
"eighty-nine" to "89",
"quatre-vingt-neuf" to "89",
"تسعة و ثمانون" to "89",
"ninety" to "90",
"quatre-vingt-dix" to "90",
"تسعون" to "90",
"ninety-one" to "91",
"quatre-vingt-onze" to "91",
"واحد و تسعون" to "91",
"ninety-two" to "92",
"quatre-vingt-douze" to "92",
"اثنان و تسعون" to "92",
"ninety-three" to "93",
"quatre-vingt-treize" to "93",
"ثلاثة و تسعون" to "93",
"ninety-four" to "94",
"quatre-vingt-quatorze" to "94",
"أربعة و تسعون" to "94",
"ninety-five" to "95",
"quatre-vingt-quinze" to "95",
"خمسة و تسعون" to "95",
"ninety-six" to "96",
"quatre-vingt-seize" to "96",
"ستة و تسعون" to "96",
"ninety-seven" to "97",
"quatre-vingt-dix-sept" to "97",
"سبعة و تسعون" to "97",
"ninety-eight" to "98",
"quatre-vingt-dix-huit" to "98",
"ثمانية و تسعون" to "98",
"ninety-nine" to "99",
"quatre-vingt-dix-neuf" to "99",
"تسعة و تسعون" to "99",
"one hundred" to "100",
"cent" to "100",
"مائة" to "100",
"عشرين" to "20",
"واحد و عشرين" to "21",
"اثنان و عشرين" to "22",
"ثلاثة و عشرين" to "23",
"أربعة و عشرين" to "24",
"خمسة و عشرين" to "25",
"ستة و عشرين" to "26",
"سبعة و عشرين" to "27",
"ثمانية و عشرين" to "28",
"تسعة و عشرين" to "29",
"ثلاثين" to "30",
"واحد و ثلاثين" to "31",
"اثنان و ثلاثين" to "32",
"ثلاثة و ثلاثين" to "33",
"أربعة و ثلاثين" to "34",
"خمسة و ثلاثين" to "35",
"ستة و ثلاثين" to "36",
"سبعة و ثلاثين" to "37",
"ثمانية و ثلاثين" to "38",
"تسعة و ثلاثين" to "39",
"أربعين" to "40",
"واحد و أربعين" to "41",
"اثنان و أربعين" to "42",
"ثلاثة و أربعين" to "43",
"أربعة و أربعين" to "44",
"خمسة و أربعين" to "45",
"ستة و أربعين" to "46",
"سبعة و أربعين" to "47",
"ثمانية و أربعين" to "48",
"تسعة و أربعين" to "49",
"خمسين" to "50",
"واحد و خمسين" to "51",
"اثنان و خمسين" to "52",
"ثلاثة و خمسين" to "53",
"أربعة و خمسين" to "54",
"خمسة و خمسين" to "55",
"ستة و خمسين" to "56",
"سبعة و خمسين" to "57",
"ثمانية و خمسين" to "58",
"تسعة و خمسين" to "59",
"ستين" to "60",
"واحد و ستين" to "61",
"اثنان و ستين" to "62",
"ثلاثة و ستين" to "63",
"أربعة و ستين" to "64",
"خمسة و ستين" to "65",
"ستة و ستين" to "66",
"سبعة و ستين" to "67",
"ثمانية و ستين" to "68",
"تسعة و ستين" to "69",
"سبعين" to "70",
"واحد و سبعين" to "71",
"اثنان و سبعين" to "72",
"ثلاثة و سبعين" to "73",
"أربعة و سبعين" to "74",
"خمسة و سبعين" to "75",
"ستة و سبعين" to "76",
"سبعة و سبعين" to "77",
"ثمانية و سبعين" to "78",
"تسعة و سبعين" to "79",
"ثمانين" to "80",
"واحد و ثمانين" to "81",
"اثنان و ثمانين" to "82",
"ثلاثة و ثمانين" to "83",
"أربعة و ثمانين" to "84",
"خمسة و ثمانين" to "85",
"ستة و ثمانين" to "86",
"سبعة و ثمانين" to "87",
"ثمانية و ثمانين" to "88",
"تسعة و ثمانين" to "89",
"تسعين" to "90",
"واحد و تسعين" to "91",
"اثنان و تسعين" to "92",
"ثلاثة و تسعين" to "93",
"أربعة و تسعين" to "94",
"خمسة و تسعين" to "95",
"ستة و تسعين" to "96",
"سبعة و تسعين" to "97",
"ثمانية و تسعين" to "98",
"تسعة و تسعين" to "99"
).mapKeys{AnswerMatcher.normalize(it.key)}
