begin;
create function private.learning_normalize(value text) returns text language sql immutable set search_path='' as $$
 select trim(regexp_replace(regexp_replace(translate(lower(regexp_replace(normalize(value,NFKD),U&'[\0300-\036F\064B-\065F\0670\0640]','','g')),'٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹ىة’''','01234567890123456789يه  '),'[،,;:!?؟"()\[\]]',' ','g'),'\s+',' ','g'));
$$;
create function private.spelling_distance(a text,b text) returns integer language plpgsql immutable set search_path='' as $$
declare previous integer[];before integer[];row integer[];i integer;j integer;n integer:=length(a);m integer:=length(b);begin
 if n>200 or m>200 then return 201;end if;
 previous:=array(select generate_series(0,m));before:=previous;
 for i in 1..n loop
  row:=array_fill(0,array[m+1]);row[1]:=i;
  for j in 1..m loop
   row[j+1]:=least(row[j]+1,previous[j+1]+1,previous[j]+case when substr(a,i,1)=substr(b,j,1) then 0 else 1 end);
   if i>1 and j>1 and substr(a,i,1)=substr(b,j-1,1) and substr(a,i-1,1)=substr(b,j,1) then row[j+1]:=least(row[j+1],before[j-1]+1);end if;
  end loop;
  before:=previous;previous:=row;
 end loop;return previous[m+1];
end $$;
create table private.number_words(word text primary key,value text not null);
revoke all on private.number_words from public,anon,authenticated;
insert into private.number_words(word,value) values
(private.learning_normalize('zero'),'0'),
(private.learning_normalize('zéro'),'0'),
(private.learning_normalize('صفر'),'0'),
(private.learning_normalize('one'),'1'),
(private.learning_normalize('un'),'1'),
(private.learning_normalize('واحد'),'1'),
(private.learning_normalize('two'),'2'),
(private.learning_normalize('deux'),'2'),
(private.learning_normalize('اثنان'),'2'),
(private.learning_normalize('three'),'3'),
(private.learning_normalize('trois'),'3'),
(private.learning_normalize('ثلاثة'),'3'),
(private.learning_normalize('four'),'4'),
(private.learning_normalize('quatre'),'4'),
(private.learning_normalize('أربعة'),'4'),
(private.learning_normalize('five'),'5'),
(private.learning_normalize('cinq'),'5'),
(private.learning_normalize('خمسة'),'5'),
(private.learning_normalize('six'),'6'),
(private.learning_normalize('six'),'6'),
(private.learning_normalize('ستة'),'6'),
(private.learning_normalize('seven'),'7'),
(private.learning_normalize('sept'),'7'),
(private.learning_normalize('سبعة'),'7'),
(private.learning_normalize('eight'),'8'),
(private.learning_normalize('huit'),'8'),
(private.learning_normalize('ثمانية'),'8'),
(private.learning_normalize('nine'),'9'),
(private.learning_normalize('neuf'),'9'),
(private.learning_normalize('تسعة'),'9'),
(private.learning_normalize('ten'),'10'),
(private.learning_normalize('dix'),'10'),
(private.learning_normalize('عشرة'),'10'),
(private.learning_normalize('eleven'),'11'),
(private.learning_normalize('onze'),'11'),
(private.learning_normalize('أحد عشر'),'11'),
(private.learning_normalize('twelve'),'12'),
(private.learning_normalize('douze'),'12'),
(private.learning_normalize('اثنا عشر'),'12'),
(private.learning_normalize('thirteen'),'13'),
(private.learning_normalize('treize'),'13'),
(private.learning_normalize('ثلاثة عشر'),'13'),
(private.learning_normalize('fourteen'),'14'),
(private.learning_normalize('quatorze'),'14'),
(private.learning_normalize('أربعة عشر'),'14'),
(private.learning_normalize('fifteen'),'15'),
(private.learning_normalize('quinze'),'15'),
(private.learning_normalize('خمسة عشر'),'15'),
(private.learning_normalize('sixteen'),'16'),
(private.learning_normalize('seize'),'16'),
(private.learning_normalize('ستة عشر'),'16'),
(private.learning_normalize('seventeen'),'17'),
(private.learning_normalize('dix-sept'),'17'),
(private.learning_normalize('سبعة عشر'),'17'),
(private.learning_normalize('eighteen'),'18'),
(private.learning_normalize('dix-huit'),'18'),
(private.learning_normalize('ثمانية عشر'),'18'),
(private.learning_normalize('nineteen'),'19'),
(private.learning_normalize('dix-neuf'),'19'),
(private.learning_normalize('تسعة عشر'),'19'),
(private.learning_normalize('twenty'),'20'),
(private.learning_normalize('vingt'),'20'),
(private.learning_normalize('عشرون'),'20'),
(private.learning_normalize('twenty-one'),'21'),
(private.learning_normalize('vingt et un'),'21'),
(private.learning_normalize('واحد و عشرون'),'21'),
(private.learning_normalize('twenty-two'),'22'),
(private.learning_normalize('vingt-deux'),'22'),
(private.learning_normalize('اثنان و عشرون'),'22'),
(private.learning_normalize('twenty-three'),'23'),
(private.learning_normalize('vingt-trois'),'23'),
(private.learning_normalize('ثلاثة و عشرون'),'23'),
(private.learning_normalize('twenty-four'),'24'),
(private.learning_normalize('vingt-quatre'),'24'),
(private.learning_normalize('أربعة و عشرون'),'24'),
(private.learning_normalize('twenty-five'),'25'),
(private.learning_normalize('vingt-cinq'),'25'),
(private.learning_normalize('خمسة و عشرون'),'25'),
(private.learning_normalize('twenty-six'),'26'),
(private.learning_normalize('vingt-six'),'26'),
(private.learning_normalize('ستة و عشرون'),'26'),
(private.learning_normalize('twenty-seven'),'27'),
(private.learning_normalize('vingt-sept'),'27'),
(private.learning_normalize('سبعة و عشرون'),'27'),
(private.learning_normalize('twenty-eight'),'28'),
(private.learning_normalize('vingt-huit'),'28'),
(private.learning_normalize('ثمانية و عشرون'),'28'),
(private.learning_normalize('twenty-nine'),'29'),
(private.learning_normalize('vingt-neuf'),'29'),
(private.learning_normalize('تسعة و عشرون'),'29'),
(private.learning_normalize('thirty'),'30'),
(private.learning_normalize('trente'),'30'),
(private.learning_normalize('ثلاثون'),'30'),
(private.learning_normalize('thirty-one'),'31'),
(private.learning_normalize('trente et un'),'31'),
(private.learning_normalize('واحد و ثلاثون'),'31'),
(private.learning_normalize('thirty-two'),'32'),
(private.learning_normalize('trente-deux'),'32'),
(private.learning_normalize('اثنان و ثلاثون'),'32'),
(private.learning_normalize('thirty-three'),'33'),
(private.learning_normalize('trente-trois'),'33'),
(private.learning_normalize('ثلاثة و ثلاثون'),'33'),
(private.learning_normalize('thirty-four'),'34'),
(private.learning_normalize('trente-quatre'),'34'),
(private.learning_normalize('أربعة و ثلاثون'),'34'),
(private.learning_normalize('thirty-five'),'35'),
(private.learning_normalize('trente-cinq'),'35'),
(private.learning_normalize('خمسة و ثلاثون'),'35'),
(private.learning_normalize('thirty-six'),'36'),
(private.learning_normalize('trente-six'),'36'),
(private.learning_normalize('ستة و ثلاثون'),'36'),
(private.learning_normalize('thirty-seven'),'37'),
(private.learning_normalize('trente-sept'),'37'),
(private.learning_normalize('سبعة و ثلاثون'),'37'),
(private.learning_normalize('thirty-eight'),'38'),
(private.learning_normalize('trente-huit'),'38'),
(private.learning_normalize('ثمانية و ثلاثون'),'38'),
(private.learning_normalize('thirty-nine'),'39'),
(private.learning_normalize('trente-neuf'),'39'),
(private.learning_normalize('تسعة و ثلاثون'),'39'),
(private.learning_normalize('forty'),'40'),
(private.learning_normalize('quarante'),'40'),
(private.learning_normalize('أربعون'),'40'),
(private.learning_normalize('forty-one'),'41'),
(private.learning_normalize('quarante et un'),'41'),
(private.learning_normalize('واحد و أربعون'),'41'),
(private.learning_normalize('forty-two'),'42'),
(private.learning_normalize('quarante-deux'),'42'),
(private.learning_normalize('اثنان و أربعون'),'42'),
(private.learning_normalize('forty-three'),'43'),
(private.learning_normalize('quarante-trois'),'43'),
(private.learning_normalize('ثلاثة و أربعون'),'43'),
(private.learning_normalize('forty-four'),'44'),
(private.learning_normalize('quarante-quatre'),'44'),
(private.learning_normalize('أربعة و أربعون'),'44'),
(private.learning_normalize('forty-five'),'45'),
(private.learning_normalize('quarante-cinq'),'45'),
(private.learning_normalize('خمسة و أربعون'),'45'),
(private.learning_normalize('forty-six'),'46'),
(private.learning_normalize('quarante-six'),'46'),
(private.learning_normalize('ستة و أربعون'),'46'),
(private.learning_normalize('forty-seven'),'47'),
(private.learning_normalize('quarante-sept'),'47'),
(private.learning_normalize('سبعة و أربعون'),'47'),
(private.learning_normalize('forty-eight'),'48'),
(private.learning_normalize('quarante-huit'),'48'),
(private.learning_normalize('ثمانية و أربعون'),'48'),
(private.learning_normalize('forty-nine'),'49'),
(private.learning_normalize('quarante-neuf'),'49'),
(private.learning_normalize('تسعة و أربعون'),'49'),
(private.learning_normalize('fifty'),'50'),
(private.learning_normalize('cinquante'),'50'),
(private.learning_normalize('خمسون'),'50'),
(private.learning_normalize('fifty-one'),'51'),
(private.learning_normalize('cinquante et un'),'51'),
(private.learning_normalize('واحد و خمسون'),'51'),
(private.learning_normalize('fifty-two'),'52'),
(private.learning_normalize('cinquante-deux'),'52'),
(private.learning_normalize('اثنان و خمسون'),'52'),
(private.learning_normalize('fifty-three'),'53'),
(private.learning_normalize('cinquante-trois'),'53'),
(private.learning_normalize('ثلاثة و خمسون'),'53'),
(private.learning_normalize('fifty-four'),'54'),
(private.learning_normalize('cinquante-quatre'),'54'),
(private.learning_normalize('أربعة و خمسون'),'54'),
(private.learning_normalize('fifty-five'),'55'),
(private.learning_normalize('cinquante-cinq'),'55'),
(private.learning_normalize('خمسة و خمسون'),'55'),
(private.learning_normalize('fifty-six'),'56'),
(private.learning_normalize('cinquante-six'),'56'),
(private.learning_normalize('ستة و خمسون'),'56'),
(private.learning_normalize('fifty-seven'),'57'),
(private.learning_normalize('cinquante-sept'),'57'),
(private.learning_normalize('سبعة و خمسون'),'57'),
(private.learning_normalize('fifty-eight'),'58'),
(private.learning_normalize('cinquante-huit'),'58'),
(private.learning_normalize('ثمانية و خمسون'),'58'),
(private.learning_normalize('fifty-nine'),'59'),
(private.learning_normalize('cinquante-neuf'),'59'),
(private.learning_normalize('تسعة و خمسون'),'59'),
(private.learning_normalize('sixty'),'60'),
(private.learning_normalize('soixante'),'60'),
(private.learning_normalize('ستون'),'60'),
(private.learning_normalize('sixty-one'),'61'),
(private.learning_normalize('soixante et un'),'61'),
(private.learning_normalize('واحد و ستون'),'61'),
(private.learning_normalize('sixty-two'),'62'),
(private.learning_normalize('soixante-deux'),'62'),
(private.learning_normalize('اثنان و ستون'),'62'),
(private.learning_normalize('sixty-three'),'63'),
(private.learning_normalize('soixante-trois'),'63'),
(private.learning_normalize('ثلاثة و ستون'),'63'),
(private.learning_normalize('sixty-four'),'64'),
(private.learning_normalize('soixante-quatre'),'64'),
(private.learning_normalize('أربعة و ستون'),'64'),
(private.learning_normalize('sixty-five'),'65'),
(private.learning_normalize('soixante-cinq'),'65'),
(private.learning_normalize('خمسة و ستون'),'65'),
(private.learning_normalize('sixty-six'),'66'),
(private.learning_normalize('soixante-six'),'66'),
(private.learning_normalize('ستة و ستون'),'66'),
(private.learning_normalize('sixty-seven'),'67'),
(private.learning_normalize('soixante-sept'),'67'),
(private.learning_normalize('سبعة و ستون'),'67'),
(private.learning_normalize('sixty-eight'),'68'),
(private.learning_normalize('soixante-huit'),'68'),
(private.learning_normalize('ثمانية و ستون'),'68'),
(private.learning_normalize('sixty-nine'),'69'),
(private.learning_normalize('soixante-neuf'),'69'),
(private.learning_normalize('تسعة و ستون'),'69'),
(private.learning_normalize('seventy'),'70'),
(private.learning_normalize('soixante-dix'),'70'),
(private.learning_normalize('سبعون'),'70'),
(private.learning_normalize('seventy-one'),'71'),
(private.learning_normalize('soixante et onze'),'71'),
(private.learning_normalize('واحد و سبعون'),'71'),
(private.learning_normalize('seventy-two'),'72'),
(private.learning_normalize('soixante-douze'),'72'),
(private.learning_normalize('اثنان و سبعون'),'72'),
(private.learning_normalize('seventy-three'),'73'),
(private.learning_normalize('soixante-treize'),'73'),
(private.learning_normalize('ثلاثة و سبعون'),'73'),
(private.learning_normalize('seventy-four'),'74'),
(private.learning_normalize('soixante-quatorze'),'74'),
(private.learning_normalize('أربعة و سبعون'),'74'),
(private.learning_normalize('seventy-five'),'75'),
(private.learning_normalize('soixante-quinze'),'75'),
(private.learning_normalize('خمسة و سبعون'),'75'),
(private.learning_normalize('seventy-six'),'76'),
(private.learning_normalize('soixante-seize'),'76'),
(private.learning_normalize('ستة و سبعون'),'76'),
(private.learning_normalize('seventy-seven'),'77'),
(private.learning_normalize('soixante-dix-sept'),'77'),
(private.learning_normalize('سبعة و سبعون'),'77'),
(private.learning_normalize('seventy-eight'),'78'),
(private.learning_normalize('soixante-dix-huit'),'78'),
(private.learning_normalize('ثمانية و سبعون'),'78'),
(private.learning_normalize('seventy-nine'),'79'),
(private.learning_normalize('soixante-dix-neuf'),'79'),
(private.learning_normalize('تسعة و سبعون'),'79'),
(private.learning_normalize('eighty'),'80'),
(private.learning_normalize('quatre-vingts'),'80'),
(private.learning_normalize('ثمانون'),'80'),
(private.learning_normalize('eighty-one'),'81'),
(private.learning_normalize('quatre-vingt-un'),'81'),
(private.learning_normalize('واحد و ثمانون'),'81'),
(private.learning_normalize('eighty-two'),'82'),
(private.learning_normalize('quatre-vingt-deux'),'82'),
(private.learning_normalize('اثنان و ثمانون'),'82'),
(private.learning_normalize('eighty-three'),'83'),
(private.learning_normalize('quatre-vingt-trois'),'83'),
(private.learning_normalize('ثلاثة و ثمانون'),'83'),
(private.learning_normalize('eighty-four'),'84'),
(private.learning_normalize('quatre-vingt-quatre'),'84'),
(private.learning_normalize('أربعة و ثمانون'),'84'),
(private.learning_normalize('eighty-five'),'85'),
(private.learning_normalize('quatre-vingt-cinq'),'85'),
(private.learning_normalize('خمسة و ثمانون'),'85'),
(private.learning_normalize('eighty-six'),'86'),
(private.learning_normalize('quatre-vingt-six'),'86'),
(private.learning_normalize('ستة و ثمانون'),'86'),
(private.learning_normalize('eighty-seven'),'87'),
(private.learning_normalize('quatre-vingt-sept'),'87'),
(private.learning_normalize('سبعة و ثمانون'),'87'),
(private.learning_normalize('eighty-eight'),'88'),
(private.learning_normalize('quatre-vingt-huit'),'88'),
(private.learning_normalize('ثمانية و ثمانون'),'88'),
(private.learning_normalize('eighty-nine'),'89'),
(private.learning_normalize('quatre-vingt-neuf'),'89'),
(private.learning_normalize('تسعة و ثمانون'),'89'),
(private.learning_normalize('ninety'),'90'),
(private.learning_normalize('quatre-vingt-dix'),'90'),
(private.learning_normalize('تسعون'),'90'),
(private.learning_normalize('ninety-one'),'91'),
(private.learning_normalize('quatre-vingt-onze'),'91'),
(private.learning_normalize('واحد و تسعون'),'91'),
(private.learning_normalize('ninety-two'),'92'),
(private.learning_normalize('quatre-vingt-douze'),'92'),
(private.learning_normalize('اثنان و تسعون'),'92'),
(private.learning_normalize('ninety-three'),'93'),
(private.learning_normalize('quatre-vingt-treize'),'93'),
(private.learning_normalize('ثلاثة و تسعون'),'93'),
(private.learning_normalize('ninety-four'),'94'),
(private.learning_normalize('quatre-vingt-quatorze'),'94'),
(private.learning_normalize('أربعة و تسعون'),'94'),
(private.learning_normalize('ninety-five'),'95'),
(private.learning_normalize('quatre-vingt-quinze'),'95'),
(private.learning_normalize('خمسة و تسعون'),'95'),
(private.learning_normalize('ninety-six'),'96'),
(private.learning_normalize('quatre-vingt-seize'),'96'),
(private.learning_normalize('ستة و تسعون'),'96'),
(private.learning_normalize('ninety-seven'),'97'),
(private.learning_normalize('quatre-vingt-dix-sept'),'97'),
(private.learning_normalize('سبعة و تسعون'),'97'),
(private.learning_normalize('ninety-eight'),'98'),
(private.learning_normalize('quatre-vingt-dix-huit'),'98'),
(private.learning_normalize('ثمانية و تسعون'),'98'),
(private.learning_normalize('ninety-nine'),'99'),
(private.learning_normalize('quatre-vingt-dix-neuf'),'99'),
(private.learning_normalize('تسعة و تسعون'),'99'),
(private.learning_normalize('one hundred'),'100'),
(private.learning_normalize('cent'),'100'),
(private.learning_normalize('مائة'),'100'),
(private.learning_normalize('عشرين'),'20'),
(private.learning_normalize('واحد و عشرين'),'21'),
(private.learning_normalize('اثنان و عشرين'),'22'),
(private.learning_normalize('ثلاثة و عشرين'),'23'),
(private.learning_normalize('أربعة و عشرين'),'24'),
(private.learning_normalize('خمسة و عشرين'),'25'),
(private.learning_normalize('ستة و عشرين'),'26'),
(private.learning_normalize('سبعة و عشرين'),'27'),
(private.learning_normalize('ثمانية و عشرين'),'28'),
(private.learning_normalize('تسعة و عشرين'),'29'),
(private.learning_normalize('ثلاثين'),'30'),
(private.learning_normalize('واحد و ثلاثين'),'31'),
(private.learning_normalize('اثنان و ثلاثين'),'32'),
(private.learning_normalize('ثلاثة و ثلاثين'),'33'),
(private.learning_normalize('أربعة و ثلاثين'),'34'),
(private.learning_normalize('خمسة و ثلاثين'),'35'),
(private.learning_normalize('ستة و ثلاثين'),'36'),
(private.learning_normalize('سبعة و ثلاثين'),'37'),
(private.learning_normalize('ثمانية و ثلاثين'),'38'),
(private.learning_normalize('تسعة و ثلاثين'),'39'),
(private.learning_normalize('أربعين'),'40'),
(private.learning_normalize('واحد و أربعين'),'41'),
(private.learning_normalize('اثنان و أربعين'),'42'),
(private.learning_normalize('ثلاثة و أربعين'),'43'),
(private.learning_normalize('أربعة و أربعين'),'44'),
(private.learning_normalize('خمسة و أربعين'),'45'),
(private.learning_normalize('ستة و أربعين'),'46'),
(private.learning_normalize('سبعة و أربعين'),'47'),
(private.learning_normalize('ثمانية و أربعين'),'48'),
(private.learning_normalize('تسعة و أربعين'),'49'),
(private.learning_normalize('خمسين'),'50'),
(private.learning_normalize('واحد و خمسين'),'51'),
(private.learning_normalize('اثنان و خمسين'),'52'),
(private.learning_normalize('ثلاثة و خمسين'),'53'),
(private.learning_normalize('أربعة و خمسين'),'54'),
(private.learning_normalize('خمسة و خمسين'),'55'),
(private.learning_normalize('ستة و خمسين'),'56'),
(private.learning_normalize('سبعة و خمسين'),'57'),
(private.learning_normalize('ثمانية و خمسين'),'58'),
(private.learning_normalize('تسعة و خمسين'),'59'),
(private.learning_normalize('ستين'),'60'),
(private.learning_normalize('واحد و ستين'),'61'),
(private.learning_normalize('اثنان و ستين'),'62'),
(private.learning_normalize('ثلاثة و ستين'),'63'),
(private.learning_normalize('أربعة و ستين'),'64'),
(private.learning_normalize('خمسة و ستين'),'65'),
(private.learning_normalize('ستة و ستين'),'66'),
(private.learning_normalize('سبعة و ستين'),'67'),
(private.learning_normalize('ثمانية و ستين'),'68'),
(private.learning_normalize('تسعة و ستين'),'69'),
(private.learning_normalize('سبعين'),'70'),
(private.learning_normalize('واحد و سبعين'),'71'),
(private.learning_normalize('اثنان و سبعين'),'72'),
(private.learning_normalize('ثلاثة و سبعين'),'73'),
(private.learning_normalize('أربعة و سبعين'),'74'),
(private.learning_normalize('خمسة و سبعين'),'75'),
(private.learning_normalize('ستة و سبعين'),'76'),
(private.learning_normalize('سبعة و سبعين'),'77'),
(private.learning_normalize('ثمانية و سبعين'),'78'),
(private.learning_normalize('تسعة و سبعين'),'79'),
(private.learning_normalize('ثمانين'),'80'),
(private.learning_normalize('واحد و ثمانين'),'81'),
(private.learning_normalize('اثنان و ثمانين'),'82'),
(private.learning_normalize('ثلاثة و ثمانين'),'83'),
(private.learning_normalize('أربعة و ثمانين'),'84'),
(private.learning_normalize('خمسة و ثمانين'),'85'),
(private.learning_normalize('ستة و ثمانين'),'86'),
(private.learning_normalize('سبعة و ثمانين'),'87'),
(private.learning_normalize('ثمانية و ثمانين'),'88'),
(private.learning_normalize('تسعة و ثمانين'),'89'),
(private.learning_normalize('تسعين'),'90'),
(private.learning_normalize('واحد و تسعين'),'91'),
(private.learning_normalize('اثنان و تسعين'),'92'),
(private.learning_normalize('ثلاثة و تسعين'),'93'),
(private.learning_normalize('أربعة و تسعين'),'94'),
(private.learning_normalize('خمسة و تسعين'),'95'),
(private.learning_normalize('ستة و تسعين'),'96'),
(private.learning_normalize('سبعة و تسعين'),'97'),
(private.learning_normalize('ثمانية و تسعين'),'98'),
(private.learning_normalize('تسعة و تسعين'),'99')
on conflict(word) do nothing;
create function private.learning_answer(input text,accepted jsonb,alternatives jsonb default '[]') returns boolean language plpgsql stable set search_path='' as $$
declare t text:=private.learning_normalize(input);a text;d integer;lim integer;len integer;best integer:=201;numeric_answer boolean;begin
 if input is null or length(input) not between 1 and 200 or t='' then return false;end if;
 if exists(select 1 from jsonb_array_elements_text(accepted) x where private.learning_normalize(x)=t) then return true;end if;
 if exists(select 1 from private.number_words n where n.word=t and not exists(select 1 from jsonb_array_elements_text(accepted) x where private.learning_normalize(x)=n.value)) then return false;end if;
 if t~'[^[:alpha:][:space:]]' then return false;end if;
 numeric_answer:=exists(select 1 from jsonb_array_elements_text(accepted) x where private.learning_normalize(x)~'^-?[0-9]+([.][0-9]+)?$');
 for a in select private.learning_normalize(x) from jsonb_array_elements_text(accepted) x loop
  if a~'[^[:alpha:][:space:]]' then continue;end if;
  len:=least(length(t),length(a));lim:=case when len<4 then 0 when len<5 then case when numeric_answer then 1 else 0 end when len<8 then 1 when len<13 then 2 else 3 end;
  if abs(length(t)-length(a))>lim then continue;end if;
  d:=private.spelling_distance(t,a);if d<=lim then best:=least(best,d);end if;
 end loop;
 if best=201 then return false;end if;
 return not exists(select 1 from jsonb_array_elements_text(alternatives) x where private.spelling_distance(t,private.learning_normalize(x))<=best and not exists(select 1 from jsonb_array_elements_text(accepted) y where private.learning_normalize(x)=private.learning_normalize(y)));
end $$;
revoke all on function private.learning_normalize(text),private.spelling_distance(text,text),private.learning_answer(text,jsonb,jsonb) from public,anon,authenticated;
create or replace function public.submit_answer(p_match uuid,p_round uuid,p_key uuid,p_action jsonb) returns jsonb
language plpgsql security definer set search_path='' as $$
declare u uuid:=private.actor(); m public.matches; r public.match_rounds; c public.content_items; answer jsonb;
 prior private.submissions; t timestamptz; points integer:=0; is_correct boolean:=false; selected text[]; option jsonb;
begin
 if not private.match_member(p_match,u) then raise exception 'not_member' using errcode='42501'; end if;
 select * into strict m from public.matches where id=p_match for update;
 -- A replay returns its existing receipt even if the deadline has since passed.
 select * into prior from private.submissions where user_id=u and idempotency_key=p_key;
 if found then
  if prior.match_id is distinct from p_match or prior.round_id is distinct from p_round or prior.action is distinct from p_action then raise exception 'idempotency_conflict'; end if;
  return jsonb_build_object('accepted',true,'receipt',prior.id);
 end if;
 perform private.advance_match(p_match);
 select * into strict r from public.match_rounds where id=p_round and match_id=p_match for update;
 t:=clock_timestamp();
 if r.status<>'active' or t<r.answer_opens_at or t>=r.deadline then raise exception 'round_not_accepting'; end if;
 if not exists(select 1 from public.match_participants where match_id=p_match and user_id=u and eligible) then raise exception 'not_eligible'; end if;
 if exists(select 1 from private.submissions where round_id=p_round and user_id=u) then raise exception 'already_submitted'; end if;
 if jsonb_typeof(p_action) is distinct from 'object' or octet_length(p_action::text)>4096 then raise exception 'invalid_action'; end if;
 select * into strict c from public.content_items where id=r.content_id;
 select a.answer into strict answer from private.content_answers a where content_id=r.content_id;
 if m.mode in ('duo','squad') and not exists(select 1 from private.team_drafts d join public.match_participants p on p.match_id=d.match_id where d.round_id=p_round and p.user_id=u and d.answerers->>p.team_id::text=u::text) then raise exception 'not_eligible';end if;
 if c.kind='question_round' then
  if (select count(*) from jsonb_object_keys(p_action))<>1 then raise exception 'invalid_action'; end if;
  if p_action ? 'option_id' then
   if jsonb_typeof(p_action->'option_id')<>'string' or not exists(select 1 from jsonb_array_elements(c.payload->'options') o where o->>'id'=p_action->>'option_id') then raise exception 'invalid_option'; end if;
   is_correct:=p_action->>'option_id'=answer->>'correct_option_id';
  elsif p_action ? 'answer' then
   if jsonb_typeof(p_action->'answer')<>'string' or length(p_action->>'answer') not between 1 and 200 then raise exception 'invalid_action'; end if;
   is_correct:=private.learning_answer(p_action->>'answer',coalesce(answer->'accepted_answers','[]'::jsonb)||(select jsonb_agg(o->>'label') from jsonb_array_elements(c.payload->'options') o where o->>'id'=answer->>'correct_option_id'),
      (select coalesce(jsonb_agg(o->>'label'),'[]') from jsonb_array_elements(c.payload->'options') o where o->>'id'<>answer->>'correct_option_id'));
  else raise exception 'invalid_action'; end if;
  if is_correct and (m.mode<>'duel' or r.first_correct is null) then
   points:=1; update public.match_rounds set first_correct=u where id=p_round;
  end if;
 elsif c.kind='image_guess' then
  if (select count(*) from jsonb_object_keys(p_action))<>1 or jsonb_typeof(p_action->'choice_ids')<>'array' or jsonb_array_length(p_action->'choice_ids')<>4 then raise exception 'invalid_selection'; end if;
  select array_agg(value) into selected from jsonb_array_elements_text(p_action->'choice_ids');
  if (select count(distinct x) from unnest(selected) x)<>4 then raise exception 'invalid_selection'; end if;
  if (select count(*) from jsonb_array_elements(answer->'choices') o where o->>'id'=any(selected))<>4 then raise exception 'invalid_selection'; end if;
  if answer->>'scoring_policy' not in ('all_selected','correct_only') or not(answer ? 'scoring_policy') then raise exception 'rules_not_approved'; end if;
  select coalesce(sum((o->>'points')::integer),0) into points from jsonb_array_elements(answer->'choices') o
  where o->>'id'=any(selected) and (answer->>'scoring_policy'='all_selected' or (o->>'correct')::boolean);
 else raise exception 'unsupported_round'; end if;
 if points<0 or points>1000 then raise exception 'invalid_content_score'; end if;
 insert into private.submissions(match_id,round_id,user_id,action,received_at,idempotency_key,awarded_points) values(p_match,p_round,u,p_action,t,p_key,points) returning * into prior;
 update public.matches set version=version+1 where id=p_match;
 -- Do not reveal correctness/point weights until the round deadline.
 return jsonb_build_object('accepted',true,'receipt',prior.id);
end $$;
commit;
